[mgr]
ratio = [1, 4, 5]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
linemode = "mtime"
scrolloff = 5

[preview]
wrap = "yes"
image_filter = "triangle"
image_quality = 70
image_delay = 30

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
